language: node_js
node_js:
  - "node"
  - "iojs"
branches:
  only:
    - master
    - develop
addons:
  code_climate
after_script:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
